### PR TITLE
Fixes #3 Fix crash with some episodes of Cooptitude and Tabletop

### LINKED ISSUE #3: I am facing errors in atleast 1 show - Co-optitude
Recently I was using the addon, while I noticed that for atleast that particular show, the same video in "Newest videos" plays fine, but when located in the "Show" itself, the latest ones fail with errors, and also appear to be named differently.

### PR DESCRIPTION
**Pull request by ktaragorn**
Fix issues with brightcove player script not being found due to a change to the HTML
Fix in a way to be more explicit about what we want and hopefully more robust
Test with Cooptitude - Secret of Evermore or TableTop - Tsuro of the seas

### CODE REVIEW

**Comment by ruuk** [comment]
Thanks for the fix.

Added you as a collaborator. I'm not expecting you to take any sort of responsibility, just hoping to make things easier.

Feel free to merge if you want and to make ANY changes to improve the add-on (or none, and just let me know of issues) and I'll test and update the repo.

You're changes look good to me, but I'm out of town for a few more days so I can't test. I've been pretty busy lately and haven't had much time to give this the love it deserves - so again, thanks :)

**Comment by ktaragorn** [comment]
Hey @ruuk, Thanks a lot for the confidence in me. This is my first OSS repo ive been added to :)

I think for now I am going to leave my changes here for you to test. I am changing the plugin code in my TV box directly so I am not in a hurry for a release. I will keep an eye out for other issues or improvements.

**Comment by ruuk** [comment]
Sounds good :)

**Comment by ktaragorn** [comment]
@ruuk do you have the time to look at this now? Ive had to re-setup my kodi, so would simplify my life to have this merged and released

**Comment by ruuk** [comment]
Sorry, somehow I missed your changes and comment until now. I'll check this out today or tomorrow. It looks good at a glance.

Thanks.

**Comment by ktaragorn** [comment]
hey @ruuk did you release a new version for this? I am still seeing errors on those files

**Comment by ruuk** [comment]
@ktaragorn: Not yet. I was going to look at merging the other pull request first.

**Pull request merged**
